config/routes.rb
Citibike::Application.routes.draw do
  devise_for :users
  resources :trips
  resources :places
  root 'trips#new'

  

end

app/models/address_validator.rb
# I know you can get this working! 
class AddressValidator < ActiveModel::Validator
  def validate(record)

    if true
    # if Geocoder.coordinates(record.origin) == nil #|| 
   		#Geocoder.coordinates(record.destination) == nil
   	#also validate for Citibike.stations.all_within(origin.lat, origin.lng, 0.5)
   	#Citibike.stations.all_within(dest.lat, dest.lng, 0.5) not being empty
      record.errors[:origin] << 'That address is not geocodable!'
      #
      #flash[:notice] = "Not geocodable!"
      #redirect_to root_path

    end
  end
end

app/models/place.rb
class Place < ActiveRecord::Base
  validates_presence_of :name
  #validates_with AddressValidator

  belongs_to :user
  geocoded_by :address, :latitude  => :lat, :longitude => :lng
  after_validation :geocode
  
end

app/models/trip.rb
=begin
There are too many comments in this class! (I know, I'm adding more, which is suboptimal.)

I know you struggled with the geocode_all and find_closest_stations / validation methods.
However, commented out code looks messy and won't help you. Trust git! Create a branch with
an alternate way of writing these methods and get it out of master.
=end
class Trip < ActiveRecord::Base
  #validates_presence_of :origin

  include ActiveModel::Validations
  #validates_with AddressValidator

  geocoded_by :origin, :latitude  => :origin_lat, 
  	:longitude => :origin_long

  geocoded_by :destination, :latitude => :destination_lat,
  	:longitude => :destination_long

  before_save :geocode_all

  def geocode_all
  	orig = Geocoder.coordinates(self.origin)
    dest = Geocoder.coordinates(self.destination)
    self.origin_lat = orig.first
    self.origin_long = orig.last
    self.destination_lat = dest.first
    self.destination_long = dest.last
  end

  # returns array of Stations sorted by distance from lat, long
  def self.find_closest_stations(lat, long)
  	nearbys = Citibike.stations.all_within(lat, long, 0.3)
    dists = {}
    nearbys.each do |sta|
      dists[sta.id] = sta.distance_from(lat, long)
  	end

    dists = dists.sort_by { |id, distance| distance }
    sorted_nearbys = []
    dists.each do |id, distance|
      sorted_nearbys << Citibike.stations.find_by_id(id)
    end

    return sorted_nearbys
  end

  #stations is array of stations sorted by distance
  def self.find_available_bike(stations)
    stations.each do |sta|
      if sta.available_bikes > 1 && sta.status == "Active"
        return sta
      end
    end
    stations.empty? ? nil : stations[0]
  end

  def self.find_available_dock(stations)
    stations.each do |sta|
      if sta.available_docks > 1 && sta.status == "Active"
        return sta
      end
    end
    stations.empty? ? nil : stations[0]
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :places
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #attr_accessible :email, :password, :password_confirmation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def new
  	@place = Place.new
  end

  def create
  	@place = Place.new(place_params)
  	@place.user_id = current_user.id
  	if @place.save
  	  redirect_to root_path
  	else
  	  render :new
  	end
  end

  def show
	  @place = Place.find(params[:id])
	  @orig = cookies["lat_lng"].split('|')
    @lat = @orig.first.to_f
    @lng = @orig.last.to_f
    @orig_stas = Trip.find_closest_stations(@lat, @lng)
    @o_sta = Trip.find_available_bike(@orig_stas)
    @dest_stas = Trip.find_closest_stations(@place.lat, @place.lng)
    @d_sta = Trip.find_available_dock(@dest_stas)
  end

  def update
    @place = Place.find(params[:id])
    if params[:commit] == 'Delete'
      Place.destroy(@place.id)
      redirect_to root_path
    elsif @place.update(place_params)
      redirect_to @place
    else
      render :new
    end
  end

  def destroy
    redirect_to root_path
  end

private
  def place_params
  	params.require('place').permit(:name, :address)
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  #before_action :set_cookie, only: :new
  SOME_SIGNIFICANT_LAT_LONG = "40.741|-73.9898"

  def set_location
    redirect_to new_trip_path unless cookies['lat_lng'].nil?
    flash[:notice] = "Please wait while we find your location...
    refresh the page if you are not redirected in a few seconds."
  end

  def index
    @trip = Trip.new
    # expire cookie here
  end

  def new
    @trip = Trip.new
#<<<<<<< HEAD
    cookies["lat_lng"] ||= "40.741|-73.9898"
    if cookies["lat_lng"] == "40.741|-73.9898"
      @zoom = 14
    else
      @zoom = 16
    end
#=======
    # What is the significance of 40.741|73.9898? Whatever it is,
    # make a method out of it and get the hard-coded numbers out of the way
    # like so
#   set_zoom_based_on_lat_lng
    #cookies["lat_lng"] = "40.7402686|-73.9895703"
    #used for marking current location and closest station
#>>>>>>> dd4c693b3fb6af47613848ee7ead32199f1308ba
	  @lat_lng = cookies["lat_lng"].split("|")
    @lat = @lat_lng.first.to_f
    @lng = @lat_lng.last.to_f
  end

  def create
  	@trip = Trip.new(trip_params)

    if @trip.save
      redirect_to @trip
    else
      flash[:error] = @trip.errors.full_messages.join(",")
      redirect_to root_path
    end
  end

  def show
  	@trip = Trip.find(params[:id])
    @orig_stations = Trip.find_closest_stations(
                @trip.origin_lat, @trip.origin_long)
    @orig_sta = Trip.find_available_bike(@orig_stations)
    
    @dest_stations = Trip.find_closest_stations(
                @trip.destination_lat, @trip.destination_long)
    @dest_sta = Trip.find_available_dock(@dest_stations)
  end

  def update
    @trip = Trip.find(params[:id])
    if @trip.update(trip_params)
      redirect_to @trip
    else
      render :new
    end
  end


private
  def trip_params
  	params.require('trip').permit(:origin, :destination)
  end

  def set_zoom_based_on_lat_lng
    cookies["lat_lng"] ||= SOME_SIGNIFICANT_LAT_LONG
    if cookies["lat_lng"] == SOME_SIGNIFICANT_LAT_LONG
      @zoom = 14
    else
      @zoom = 16
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  #require 'JSON'

  def get_stations
  	url = "http://www.citibikenyc.com/stations/json/"
  	resp = Net::HTTP.get_response(URI.parse(url))
  	data = resp.body
  	result = JSON.parse(data)
  	result["stationBeanList"]
  end

  def closest_station_coords(lat, long)
    nearbys = Citibike.stations.all_within(lat, long, 2.5)
    if nearbys.empty?
      #flash error msg and redirect to homepage?
      return [nil, nil]
    else
      sta = closest_station_id(nearbys, lat, long)
      return [sta["latitude"], sta["longitude"]]
    end
  end

  #takes array of citibike stations
  def closest_station_id(nearbys, lat, long)
    dists = Hash.new #ids as keys, distances as vals
    nearbys.each do |nearby|
      lats = lat - nearby["latitude"]
      longs = long - nearby["longitude"]
      dists[nearby["id"]] = Math.sqrt(lats*lats + longs*longs)
    end

    min = dists.values.min
    id = dists.key(min)
    Citibike.stations.find_by_id(id)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <meta name="google-site-verification" content="kOIaVSc3lcTCuWTh-L3QZzfphzvKJsdacpM83UCTRkA"/>
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDUxuJVuvsR7Fy6J5ZBThZ4zAX79mrFGbI&amp;sensor=true&amp;">
  </script>
  
  <title>Citibike</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/places/new.html.erb
<% =begin %>
Place your css files in app/assets/stylesheets!
<% =end %>

<!DOCTYPE html>
<html>
  <head>
    <style type="text/css">
      html { height: 100% }
      body { 
        height: 100%; 
        margin: 0; 
        text-align: center;
        padding-top: 70px;
      }
    </style>
  </head>

<body>

<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-10 col-xs-offset-1">
        <div class="panel panel-warning">
          <div class="panel-heading">
            <h3 class="panel-title">Add a New Place</h3>
          </div>
          <div class="panel-body">
            <%= form_for @place, role: "form" do |f| %>
              <fieldset>
                <div class="form-group has-warning">
                  <%= f.label :name, class: "sr-only" %>
                  <%= f.text_field :name, class: "form-control", placeholder: "Place name" %>
                </div>
                <div class="form-group has-warning">
                  <%= f.label :address, class: "sr-only" %>
                  <%= f.text_field :address, class: "form-control", placeholder: "Address" %>  
                </div>
                <%= f.submit "Add to Favorites", class: "btn btn-warning btn-lg btn-block" %>
              </fieldset>
            <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

</body>
</html>

app/views/places/show.html.erb
<!--
You have a well-written controller and model for your places resource. Here things go off the rails a bit. You know where to put javascripts, and you do it correctly with your trips.js file. I'm guessing you tried shoving everything - head html, javascripts - into this and other files because you were trying to debug something tricky. I understand this, but there are better ways. The Google Developer tools in Chrome are the best place to start. In general, putting everything together in one file is only going to help you debug the most esoteric issues. If you're working in rails, trust the Rails asset pipeline is serving your assets as you specified and work on isolating the issue.
-->

  <script type="text/javascript">
    var directionsService = new google.maps.DirectionsService();

    function initialize() {
      directionsDisplay = new google.maps.DirectionsRenderer();

      map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);

      directionsDisplay.setMap(map);

      <% unless @o_sta == nil || @d_sta == nil %>
        addMarker(<%= @lat %>, <%= @lng %>, "You are here", true);
        addMarker(<%=@place.lat%>, <%=@place.lng%>, "<%=@place.address%>", true);
      <% end %>
    } //end initialize
    
    google.maps.event.addDomListener(window,'load',initialize);

    <% if @o_sta != nil && @d_sta != nil %>
      calcRoute("<%= "#{@o_sta.lat}, #{@o_sta.long}" %>", "<%= "#{@d_sta.lat}, #{@d_sta.long}" %>");
    <% else %>
      calcRoute("<%= "#{@lat}, #{@lng}" %>", "<%= @place.address %>");
    <% end %>

  </script>

</head>
<body>
  <div class="container">
	<header>
	  <%= render 'shared/header' %>
	</header>


  <% if @o_sta == nil || @d_sta == nil %>
    <div class="alert alert-danger">
      <p class="text-left"><strong>Citibike is not</strong> a good way to get from <strong>(A)</strong> your current location to <strong>(B)</strong> <%= @place.name %>. Edit or delete this place below.</p>
    </div>
  <% else %>

    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h4>Current Location <small>to</small> <%=@place.name%></h4>
          </div>
          <table class="table table-hover">
            <tr>
              <td>Closest Bike (A)</td>
              <td><b class="text-success"><%= @o_sta["label"] %></b></td>
              <td><%= @o_sta["availableBikes"] %> bikes available</td>
            </tr>
            <tr>
              <td>Closest Dock (B)</td>
              <td><b class="text-danger"><%= @d_sta["label"] %></b></td>
              <td><%= @d_sta["availableDocks"] %> docks available</td>
            </tr>
          </table>
        </div>
      </div>
    </div>
  <% end %>

	
  <div class="panel panel-default">
    <div class="panel-body" id="map-canvas" style="height: 600px"/></div>
  </div>

  <h3><small>Not the place you wanted? Edit or delete it from your favorites</small></h3>
  <div class="navbar-form">
    <%= form_for @place, html: {class: "form-inline"} do |f| %>
      <div class="form-group has-warning">
        <%= f.label :name, class: "sr-only" %>
        <%= f.text_field :name, class: "form-control", placeholder: "New Name" %>
      </div>
      <div class="form-group has-warning">
        <%= f.label :address, class: "sr-only" %>
        <%= f.text_field :address, class: "form-control", placeholder: "New Address" %>
      </div>
        <%= f.submit "Update Place", class: "btn btn-warning" %>
        <%= f.submit "Delete", class: "btn btn-danger" %>
    <% end %>
  </div>
  <p>-</p>
</div>

app/views/shared/_find_stations_btn.html.erb
<a href="/"><button class="btn btn-primary navbar-btn" type="button" onclick="makeList()"><h5>Find Stations</h5></button></a>

app/views/shared/_footer.html.erb
  <nav class="navbar navbar-default " role="navigation">
    <ul class="nav navbar-nav navbar-left">
      <li><a style="cursor:pointer" onclick='alert("CitibikeBetter is a map to better help citibikers get around New York." + "\n" + "\n" + 

      "Search for directions the same way you would on Google Maps. You will be shown biking directions from the closest station to your origin with bikes available to the closest station to your destination with open docks." + "\n" + "\n" +

      "The homepage should find your current location automatically. Press Find Staitons to see a dropdown menu of nearby stations, represented on the map by orange markes. Click on a station to see its current bike/dock status." + "\n" + "\n" + 

      "You can also store your favorite places, e.g., Home, to get quick directions to a specific address from your current location.");'>What is this?</a></li>
      <li><a href="https://github.com/snebel/Citibike" target="blank">Source Code</a></li>
      <li><a class="text-primary" href="mailto:sam@samnebel.com?Subject=CitibikeBetter" target="_top">Contact</a></li>
    </ul>

    <div class="navbar navbar-nav navbar-right">
      <p class="navbar-text">Made in <strong>NYC</strong> by <a href="http://www.samnebel.com" target="blank">Sam Nebel</a></p>
    </div>
  </nav>

app/views/shared/_get_places_btn.html.erb
<a href="/users/sign_in"><button class="btn btn-primary navbar-btn" type="button"><h5>Favorite Places</h5></button></a>

app/views/shared/_header.html.erb
  
  <style>
    h1 { 
      padding-bottom: 10px;
      padding-left: 15px;
    }
  </style>



  <header>
    <nav class="navbar navbar-default" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="/"><h1 class="text-primary">CitibikeBetter</a><small> a useful map for citibikers</small></h1>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <!--<li><a href="/">Home</a></li>-->
          <li>
            <% if signed_in? %>
              <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
            <% else %>
              <%= link_to "Sign in", new_user_session_path %>   
            <% end %>
            
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </nav>
  </header>

app/views/shared/_show_places_btn.html.erb
<div class="btn-group ">
  <button type="button" class="btn navbar-btn btn-primary dropdown-toggle" data-toggle="dropdown">
    <h5>Favorite Places <span class="badge"> <%=current_user.places.size%> <span class="caret"></span></h5>
  </button>
  <ul class="dropdown-menu" role="menu">
    <% current_user.places.each do |place| %>
      <li><h5><%= link_to place.name, place%></h5></li>
    <% end %>
    <li class="divider"></li>
    <li><h6><%= link_to 'add new place', new_place_path %><h6></li>
  </ul>

app/views/shared/_show_stations_btn.html.erb
<div class="btn-group">
  <button type="button" class="btn btn-primary navbar-btn dropdown-toggle" data-toggle="dropdown" onclick="makeList()">
    <h5>Nearby Stations <span class="badge"> <%=@stas.size%> <span class="caret"></span></h5>
  </button>
  <ul class="dropdown-menu" role="menu">
    <li><h4><small>Wrong list? <%= link_to 'Refresh', '' %></small></h4>
  <% if !@stas.empty? %>
    <% @stas.each do |sta| %>
      <li><a ><h5><%= sta["label"]%></br><h4><small><%= sta.available_bikes %> bikes,  <%= sta.available_docks %> docks</small></h4></a></li>
    <% end %>
  <% else %>
    <li><h6>No stations nearby</h6></li>
  <% end %>
  </ul>
</div>

app/views/trips/new.html.erb
<script type="text/javascript">
  //GEOLOCATION API
  navigator.geolocation.getCurrentPosition(handleGeolocation, handleNoGeolocation);

  function handleGeolocation(position) {
    var lat = position.coords.latitude;
    var lng = position.coords.longitude;
    var cookie_val = lat + "|" + lng;
    document.cookie = "lat_lng=" + escape(cookie_val); path = '/places';
    setAddress(lat, lng);
    map.setCenter(new google.maps.LatLng(lat, lng));
    addMarker(lat, lng, "YOU ARE HERE", true);

    <% lat_lng = cookies["lat_lng"].split("|") %>
    <% lat = lat_lng.first.to_f %>
    <% lng = lat_lng.last.to_f %>
    <% stas = Trip.find_closest_stations(lat, lng) %>
  };

  function setAddress(latitude, longitude) {
    geocoder = new google.maps.Geocoder();
    latlng = new google.maps.LatLng(latitude, longitude);

    result = geocoder.geocode({'latLng': latlng}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
        current_address = results[0].formatted_address;
        $("#address").html(current_address); 
      }
      else
        { $("#address").html("Geocoder failed due to: " + status); }
    });
  };
  
  function initialize() {
    var mapOptions = {
      center: new google.maps.LatLng(<%=@lat%>, <%=@lng%>),
      //center: new google.maps.LatLng(40.741, -73.9898),
      zoom: <%= @zoom %>,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };

    map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);

    new google.maps.BicyclingLayer().setMap(map);

    <% get_stations.each do |sta| %>
      addMarker(<%= sta["latitude"] %>, <%= sta["longitude"] %>, "Bikes: <%= sta["availableBikes"] %> Docks: <%= sta["availableDocks"] %>")
    <% end %>
  } //end initialize

  google.maps.event.addDomListener(window, 'load', initialize);
</script>

  <% lat_lng = cookies["lat_lng"].split("|") %>
  <% lat = lat_lng.first.to_f %>
  <% lng = lat_lng.last.to_f %>
    
    
<div class="container">
  <%= render 'shared/header' %>

  <%= flash[:error] %>
  <div class="navbar-form">
    <%= form_for @trip, html: {class: "form-inline", name: "trip_search"} do |f| %>
      <div class="form-group has-info">
        <%= f.label :origin, class: "sr-only" %>
        <%= f.text_field :origin, class: "form-control", placeholder: "Origin" %>
      </div>
      <div class="form-group ">
        <%= f.label :destination, class: "sr-only" %> 
        <%= f.text_field :destination, class: "form-control", placeholder: "Destination" %>
      </div>
      <%= f.submit "Find Station Directions", class: "btn btn-info " %>
    <% end %>
  </div>

  <h3><small>Current Location (approximate):
    <a style="cursor:pointer" onclick="link_address();">
      <div id="address" style="display: inline-block">
        searching...
      </div>
    </a></small>
  </h3>

  <!-- button logic -->
  <div class="bs-example">
    <% if cookies["lat_lng"] == "40.741|-73.9898" %>
        <%= render 'shared/find_stations_btn' %>
      <% if signed_in? %>
        <%= render 'shared/show_places_btn' %>
      <% else %>
       <%= render 'shared/get_places_btn' %>
      <% end %>
    <% else %>

      <div class="btn-group">
        <button type="button" class="btn btn-primary navbar-btn dropdown-toggle" data-toggle="dropdown">
        <h5>Nearby Stations <span class="badge"> <%=stas.size%> <span class="caret"></span></h5></button>
          <ul class="dropdown-menu" role="menu">
            <li><h4><small>Wrong list? <%= link_to 'Refresh', '' %></small></h4>
            <% if !stas.empty? %>
              <% stas.each do |sta| %>
                <li><a ><h5><%= sta["label"]%></br><h4><small><%= sta.available_bikes %> bikes,  <%= sta.available_docks %> docks</small></h4></a></li>
              <% end %>
            <% else %>
              <li><h6>No stations nearby</h6></li>
            <% end %>
          </ul>
      </div>

     <% if signed_in? %>
       <%= render 'shared/show_places_btn' %>
      <% else %>
        <%= render 'shared/get_places_btn' %>
      <% end %>
    <% end %>
  </div>

  <div class="panel panel-default">
    <div class="panel-body" id="map-canvas" style="height: 600px"></div>
  </div>
  
  <%= render 'shared/footer' %>
</div>

app/views/trips/set_location.html.erb
<% =begin %>
All of this belongs in its own file. Also, you should look into sharing your javascripts between files to clean up duplication.
<% =end %>

<script type="text/javascript">
  navigator.geolocation.getCurrentPosition(handleGeolocation, handleNoGeolocation);

  function handleGeolocation(position) {
    var cookie_val = position.coords.latitude + "|" + position.coords.longitude;
    document.cookie = "lat_lng=" + escape(cookie_val);

    geocoder = new google.maps.Geocoder();
    latlng = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);

    var current_address;

    geocoder.geocode({'latLng': latlng}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
        current_address = results[0].formatted_address;
      }
      else {
        alert("Geocoder failed due to: " + status);
      }
    });
    //var current_address = // google maps api call to look up address from lat lng
    $("#address").html("Current Location (approximatehdgf): " + current_address)
  };

  function handleNoGeolocation(error) {
    switch(error.code)
    {
      case error.PERMISSION_DENIED:
        return "User denied the request for Geolocation.";
      case error.POSITION_UNAVAILABLE:
        return "Location information is unavailable.";
      case error.TIMEOUT:
        return "The request to get user location timed out.";
      case error.UNKNOWN_ERROR:
        return "An unknown error occurred.";
    }
  }
</script>
<% if flash[:notice] %>
    <div id="notice"><%= flash[:notice] %></div>
<% end %>

app/views/trips/show.html.erb
  <script type="text/javascript">
    var directionsService = new google.maps.DirectionsService();
    var directionsDisplay;
    var map;
    function initialize() {
      directionsDisplay = new google.maps.DirectionsRenderer();

      map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);

      directionsDisplay.setMap(map);

      <% unless @orig_sta == nil || @dest_sta == nil %>
        addMarker(<%=@trip.origin_lat%>, <%=@trip.origin_long%>, "<%= @trip.origin %>", true);
        addMarker(<%= @orig_sta.lat %>, <%= @orig_sta.long %>, "(A) <%= @orig_sta["label"] %>", true);
        addMarker(<%=@trip.destination_lat%>, <%=@trip.destination_long%>, "<%= @trip.destination %>", true);
        addMarker(<%= @dest_sta.lat %>, <%= @dest_sta.long %>, "(B) <%= @dest_sta["label"] %>", true);
      <% end %>
    } //end initialize

    /* show places initialize function
    function initialize() {
      directionsDisplay = new google.maps.DirectionsRenderer();

      map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);

      directionsDisplay.setMap(map);

      <% unless @o_sta == nil || @d_sta == nil %>
        addMarker(<%= @lat %>, <%= @lng %>, "You are here", true);
        addMarker(<%=@place.lat%>, <%=@place.lng%>, "<%=@place.address%>", true);
      <% end %>
    } //end initialize
    */

    google.maps.event.addDomListener(window,'load',initialize);

    //show station-station directions
    <% if @orig_sta != nil && @dest_sta != nil %>
      calcRoute("<%= "#{@orig_sta.lat}, #{@orig_sta.long}" %>", "<%= "#{@dest_sta.lat}, #{@dest_sta.long}" %>");
    <% else %>
      calcRoute("<%= @trip.origin %>", "<%= @trip.destination %>");
    <% end %>
  </script>



  <div class="container">
  	<header>
  	  <%= render 'shared/header' %>
  	</header>

    <% if @orig_sta == nil || @dest_sta == nil %>
      <div class="alert alert-danger">
        <p class="text-left"><strong>Citibike is not a good choice for this route.</strong> Try searching again</p>
      </div>
    <% else %>
      <div class="row">
        <div class="col-sm-8 col-sm-offset-2">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title"><%= @trip.origin%> <small>to</small> <%=@trip.destination%></h3>
          </div>
          <table class="table table-hover">
            <tr class="">
              <td>Closest Bike (A)</td>
              <!--<td>Closest Bike:</td>-->
              <td><p class="text-success"><strong><%= @orig_sta["label"] %></strong></p></td>
              <td><%= @orig_sta.available_bikes %> bikes available</td>
            </tr>
            <tr class="">
              <td>Closest Dock (B)</td>
              <!--<td>Closest Dock:</td>-->
              <td><p class="text-danger"><strong><%=@dest_sta["label"]%></strong></p></td>
              <td><%= @dest_sta.available_docks %> docks available</td>
            </tr>
          </table>
        </div>
        </div>
      </div>
    <% end %>
    <!-- END TABLE -->

    <div class="panel panel-default">
  	  <div class="panel-body" id="map-canvas" style="height: 600px"/></div>
    </div>

    <h3><small>Not the trip you wanted? Try searching again</small></h3>

    <div class="navbar-form">
      <%= form_for @trip, html: {class: "form-inline"} do |f| %>
      <div class="form-group">
        <%= f.label :origin, class: "sr-only" %>
        <%= f.text_field :origin, class: "form-control", placeholder: "Origin" %>
      </div>
      <div class="form-group">
        <%= f.label :destination, class: "sr-only" %> 
        <%= f.text_field :destination, class: "form-control", placeholder: "Destination" %>
      </div>
        <%= f.submit "Adjust Trip", class: "btn btn-info" %>
      <% end %>
    </div>
    <p>-</p>
  </div>